---
site_name: arch linux
site_description: howtos and recipes for arch linux

# navigation structure
nav:
  - Installation: installation.md

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top

plugins:
  - techdocs-core
  - search

# https://squidfunk.github.io/mkdocs-material/reference/
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - admonition
