---
site_name: arch linux
site_description: howtos and recipes for arch linux

nav:
  - Overview: index.md
  - Installation: installation.md
  - Reset: reset.md
  - Btrfs: btrfs.md
  - Docker: docker.md
  - Nix: nix.md
  - Nvidia: nvidia.md
  - WSL: wsl.md

plugins:
  - techdocs-core
